labrosite_article_adminpage:
    resource: "@LabrositeArticleBundle/Resources/config/routing/admin_article.yml"
    prefix:   /admin/article

labrosite_article_homepage:
    path:     /article/{name}
    defaults: { _controller: LabrositeArticleBundle:Default:index }
